version: '3.8'

services:
  foxes:
    build:
      context: .
      dockerfile: Dockerfile
    image: foxes:latest
    container_name: FOXES
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - .:/workspace/FOXES
      - /data/FOXES_Data:/data/FOXES_Data
    stdin_open: true
    tty: true
    restart: unless-stopped
    shm_size: '8gb'
    command: conda run -n foxes bash -c "tail -f /dev/null"

