base_data_dir: "/mnt/data/COMBINED/"  # Change this line for different datasets
output_path: "${base_data_dir}/output/patch.csv"
weight_path: "${base_data_dir}/patch_weights/"
flux_path: "${base_data_dir}/patch_flux/"
mc:
  active: "false"
  runs: 5
# Enable or disable MC Dropout
# Data paths (automatically constructed from base directories)
Stereo: "false"
Stereo_data:
    stereo_img_dir: "/mnt/data/ML-Ready-mixed/STEREO_processed"
    sxr_dir: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed/SXR"
    sxr_norm_path: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed/SXR/normalized_sxr.npy"
SolO: "false"
SolO_data:
    solo_img_dir: "/mnt/data/ML-Ready_clean/SolO/SolO/ML-Ready-SolO"
    sxr_dir: "${base_data_dir}/SXR"
    sxr_norm_path: "${base_data_dir}/SolO/SXR/normalized_sxr.npy"
model: "vit"  # Options: "cnn", "vit", "ViT Custom"
wavelengths: [94,131,171, 193, 211, 304]  # AIA wavelengths in Angstroms
data:
  aia_dir:
    "${base_data_dir}/AIA-SPLIT"
  sxr_dir:
    "${base_data_dir}/SXR-SPLIT"
  sxr_norm_path:
    "${base_data_dir}/SXR-SPLIT/normalized_sxr.npy"
  checkpoint_path:
    "/mnt/data/COMBINED/new-checkpoint/vit-patch-model-2d-embeddings-epoch=44-val_total_loss=0.0394.ckpt"


