# Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-READY/"  # Change this line for different datasets
output_path: "${base_data_dir}/output/baseline-model-more-complex-STEREO.csv"
weight_path: "${base_data_dir}/baseline-model/"
mc:
  active: "false"
  runs: 5
# Enable or disable MC Dropout
# Data paths (automatically constructed from base directories)
Stereo: "false"
Stereo_data:
    stereo_img_dir: "/mnt/data/ML-Ready-mixed/STEREO_processed"
    sxr_dir: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed/SXR"
    sxr_norm_path: "/mnt/data/ML-READY/SXR/normalized_sxr.npy"
SolO: "false"
SolO_data:
    solo_img_dir: "/mnt/data/ML-Ready_clean/SolO/SolO/ML-Ready-SolO"
    sxr_dir: "${base_data_dir}/SXR"
    sxr_norm_path: "${base_data_dir}/SolO/SXR/normalized_sxr.npy"

model: "hybrid"  # Options: "vit", "hybrid"
wavelengths: [171, 193, 211, 304]  # AIA wavelengths in Angstroms

# Model parameters
model_params:
  input_size: 512
  patch_size: 16
  batch_size: 100
  no_weights: false  # Set to true to skip saving attention weights

megsai:
  cnn_model: "updated"  # Must match the training config
  cnn_dp: 0.2

data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "/mnt/data/ML-READY/SXR/normalized_sxr.npy"
  checkpoint_path:
    "/mnt/data/COMBINED/new-checkpoint/vit-patch-model-2d-embeddings-claude-suggested-weights-epoch=30-val_total_loss=0.0385.ckpt"


