#Base directories - change these to switch datasets
base_data_dir: "/mnt/data/COMBINED"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/COMBINED"    # Change this line for different datasets
wavelengths: [171, 193, 211, 304]  # AIA wavelengths in Angstroms

# GPU configuration
gpu_id: 1  # GPU device ID to use (0, 1, 2, etc.) or -1 for CPU only
# Model configuration
selected_model: "ViTPatch"  # Options: "hybrid", "vit", "fusion", "vitpatch"
batch_size:    64
epochs:        250
oversample: false
balance_strategy: "upsample_minority"
calculate_base_weights: false  # Whether to calculate class-based weights for loss function

megsai:
  architecture: "cnn"
  seed: 42
  lr: 0.0001
  cnn_model: "updated"
  cnn_dp: 0.2
  weight_decay: 1e-5
  cosine_restart_T0: 50
  cosine_restart_Tmult: 2
  cosine_eta_min: 1e-7

vit_custom:
    embed_dim: 512
    num_channels: 4
    num_classes: 1
    patch_size: 16
    num_patches: 1024
    hidden_dim: 512
    num_heads: 8
    num_layers: 6
    dropout: 0.1
    lr: 0.0001


fusion:
  scalar_branch: "hybrid"        # or "linear"
  lr: 0.0001
  lambda_vit_to_target: 0.3
  lambda_scalar_to_target: 0.1
  learnable_gate: true
  gate_init_bias: 5.0
  scalar_kwargs:
    d_input: 6
    d_output: 1
    cnn_model: "updated"
    cnn_dp: 0.75


# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA-SPLIT"
  sxr_dir:
    "${base_data_dir}/SXR-SPLIT"
  sxr_norm_path:
    "${base_data_dir}/SXR-SPLIT/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/new-checkpoint/"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: Model Testing
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: vit-patch-model-2d-embeddings-reduced-sensitivity-STEREO
  notes: Regression from AIA images (6 channels) to GOES SXR flux