
#Base directories - change these to switch datasets
base_data_dir: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed"  # Change this line for different datasets
base_checkpoint_dir: "/mnt/data/ML-Ready-mixed/ML-Ready-mixed"    # Change this line for different datasets
wavelengths: [94, 131, 171, 193, 211, 304]  # AIA wavelengths in Angstroms
# Model configuration
selected_model: "ViT Patch"  # Options: "cnn", "vit",
batch_size:    4
epochs:        500
oversample: false
balance_strategy: "upsample_minority"

megsai:
  architecture: "cnn"
  seed: 42
  lr: 0.0001
  cnn_model: "original"
  cnn_dp: 0.2

vit_custom:
    embed_dim: 512
    num_channels: 6
    num_classes: 1
    patch_size: 8
    num_patches: 4096
    hidden_dim: 512
    num_heads: 8
    num_layers: 6
    dropout: 0.1
    lr: 0.0001

# Data paths (automatically constructed from base directories)
data:
  aia_dir:
    "${base_data_dir}/AIA"
  sxr_dir:
    "${base_data_dir}/SXR"
  sxr_norm_path:
    "${base_data_dir}/SXR/normalized_sxr.npy"
  checkpoints_dir:
    "${base_checkpoint_dir}/new-checkpoint/"

wandb:
  entity: jayantbiradar619-university-of-arizona # Use your exact W&B username
  project: ViT Loss Function Testing For Patches
  job_type: training
  tags:
    - aia
    - sxr
    - regression
  wb_name: vit-8-patch
  notes: Regression from AIA images (6 channels) to GOES SXR flux